### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by joonakauranen** [ptuomola/ot-harjoitustyo#3]
### Koodikatselmointi

Ladattu 4.12.2020 klo 13.44

Aihe on erittäin kiinnostava. Uskon, että sovellukselle olisi yksityislentäjien keskuudessa käyttöä.

Tarkastelin sovellusta koodikatselmoinnin ohjeiden ja kurssilla määriteltyjen koodin laatuvaatimusten näkökulmasta. Sovelluksen tekijä vaikuttaa olevan hieman kokeneempi ohjelmoija kuin itse olen, joten kirjoittamani maininnat kannattaa lukea tämä kokemusero mielessä pitäen.

Lisäsin huomioihin parannusehdotuksia tai vinkkejä kun sellaisia keksin.

### Tekemäni huomiot

Testeissä jokainen testi luo Pilot-olion samoilla attribuuteilla. Parannusehdotuksena voit harkita @before-merkinnällä varustettua setUp()-metodia jolla saisit “tuoreen” olion käyttöön kaikille luokan testeille.

Testit testaavat erillisiä kokonaisuuksia, mutta toisaalta moni testi testaa useaa eri asiaa. Kurssimateriaalin mukaan suositeltava käytäntö on, että kukin testi testaa vain yhtä asiaa. Näin siitäkin huolimatta, että yhteen testiin on mahdollista laittaa useampia assert:eja. Testejä voisi siis jakaa pienempiin osiin.

Service-luokan muuttujien nimentä samankaltaisilla lyhenteillä (ar, as, ap, fr, frl jne) vaikeutti koodin luettavuutta ulkopuolisen näkökulmasta. Samaa käytäntöä esiintyy vähemmissä määrin muissakin luokissa. Korjaisin nimiä intuitiivisemmin ymmärrettäviksi.

Useissa luokissa on (ehkä vain toistaiseksi?) käyttämättömiä importteja. Jos käytät NetBeansia niin tämä on tarvittaessa helppo korjata: Source → Fix Imports. 

Luokassa MainController on melko pitkiä ehtolauseita. Koodia olisi helpompi lukea jos niiden logiikka olisi luokkametodeissa. Pitkien ehtolauseiden sijaan hyvin nimetyt metodit helpottaisivat initialize():n hahmottamista.

Pakkauksen ui luokissa on pitkähköjä metodeja. Esimerkkinä ainakin luokan CreatePilotController metodi handleCreatePilotAction() ylittää kurssilla toivotun max 20 rivin pituuden. En tunne JavaFX:ää kovin hyvin, mutta mahdollisesti metodit ovat pilkottavissa pienempiin osiin.

Käyttöliittymä toimii hyvin ja on intuitiivinen. Muutamia pieniä huomiota siitä:

View Flightsia tutkittuani huomasin etsiväni “Back”-nappia tai nuolta josta palata takaisin päänäkymään. OK-nappi kyllä toki toimii aivan yhtä hyvin

Flight detailsissa ei voinut kirjoittaa “Pilot”-kenttään.

### Loppusanat

Kaikkiaan koodi näyttää mielestäni tosi hyvältä. Vertailin kohta kohdalta kurssin laatuvaatimuksiin ja mielestäni työ täyttää nämä ehdot merkittävältä osin. Positiivista palautetta voi antaa, joka osa-alueesta. Päällimmäisenä ja mielestäni erityisen maininnan arvoisena asiana mieleeni jäi sovelluksen hyödyllisyys. Oikean elämän käyttötarkoituksen omaava työ oli inspiroiva.

**Comment by ptuomola** [comment]
Kiitos palautteesta! Olen ottanut tämän huomioon jatkokehityksessä.
